# Generated by Django 4.1.6 on 2023-02-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='first_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='last_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
