# Generated by Django 4.1.6 on 2023-02-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('denied', 'Denied')], max_length=16)),
            ],
        ),
    ]
