# Generated by Django 4.1.6 on 2023-02-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_add_first_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaserPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.FloatField(default=0)),
                ('author', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.PROTECT, related_name='account', to='users.author')),
                ('teaser_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', related_query_name='account', to='accounts.teaserprice')),
            ],
        ),
    ]
